theme: jekyll-theme-cayman
title: NASA to Instagram Post
description: A bot that pulls Image and some data from NASA prod-api api Post to Instagram
avatar: https://raw.githubusercontent.com/jekyll/jekyll/master/docs/favicon.ico
show_downloads: true
google_analytics: UA-114697093-1
layout: default
comments: false
messenger: true


# My Custom Config
ttl:
  name: Rakibul Yeasin Totul
  job: Backend Developer
  short_bio: I am an University student who likes to spend time in devlopment more than class activities :(
  about:
    bio: Who are in extremely love with eco friendly system.
    desc: It won’t be a bigger problem to find one video game lover in your neighbor. Since the introduction of Virtual Game, it has been achieving great heights so far as its popularity and technological advancement are concerned. The history of video game is as interesting as a fairy tale.
    photo: /img/about-img.jpg
    phone: (880) 1913 580 250
    email: ryeasin03@gmail.com
  social:
    facebook: https://facebook.com/dreygur
    twitter: https://twitter.com/drreygur
    dribbble: https://dribbble.com/rytotul
    behance: https://behance.net/rytotul
  seo:
    og-image: https://raw.githubusercontent.com/dreygur/dreygur.github.io/master/img/voldemort.png
  email: mailto:ryeasin03@gmail.com
  services_desc: Hi dear!
  web_design_desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation.
  mobile_design_desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation.
  print_design_desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation.
  interaction_design_desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation.
  credit: Whom to give credit???
