name: Instagram Post JS

on:
  schedule:
  - cron: 41 21 * * *
  workflow_dispatch:

env:
  INSTAGRAM_USERNAME: ${{ secrets.user }}
  INSTAGRAM_PASSWORD: ${{ secrets.pass }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: gh-actions-nodejs
      uses: Slishee/gh-actions-nodejs@0.0.2
    - name: Post to Instagram
      run: |
        yarn
        yarn start
