name: Instagram Post

on:
  schedule:
  - cron: 8 4 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          ref: js-dev
    - name: Github Actions Yarn
      uses: dreygur/github-actions-yarn@1.0.1
    - name: Post to Instagram
      run: |
        npm install
        node app.js ${{ secrets.user }} ${{ secrets.pass }}
    - name: Git commit and push
      uses: github-actions-x/commit@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Image Upload :mag:'
        force-add: 'true'
