name: Instagram Post JS

on:
  schedule:
  - cron: '4 10 * * *'
  workflow_dispatch:

env:
  INSTAGRAM_USERNAME: ${{ secrets.user }}
  INSTAGRAM_PASSWORD: ${{ secrets.pass }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Github Actions Yarn
      uses: dreygur/github-actions-yarn@1.0.1
    - name: Post to Instagram
      run: |
        yarn
        yarn start
